# Generated by Django 5.2.4 on 2025-08-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dummy_field',
            field=models.BooleanField(default=True),
        ),
    ]
