# Generated by Django 5.2.4 on 2025-08-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_customuser_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dummy_field',
        ),
    ]
